FDG-4340: covering edge cases for LQE
Flipkart/hive pull request #22
Opened 2020-01-08 12:30 UTC by dileepk7

2020-01-08 12:41 UTC, jithendhir92 reviewed
LGTM

2020-01-08 12:41 UTC, jithendhir92 commented on common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
> -    LIGHT_QUERY_ENGINE_ENABLED("light.query.engine.enabled", false,
Make sure these configs are removed from config buckets after deployment.

2020-01-09 05:07 UTC, mittalnanu requested changes
please write test cases

2020-01-09 05:07 UTC, mittalnanu commented on beeline/src/java/org/apache/hive/beeline/Commands.java
> +              beeLine.getOpts().getHiveConfVariables(),
describe what post hook does

2020-01-09 13:43 UTC, mittalnanu approved these changes
LGTM

2020-01-09 13:43 UTC, merged